### PR TITLE
feat: add support for design tokens and CSS variables

### PR DESCRIPTION
**Pull request by xitij2000**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
@xitij2000 Just checking, this PR is still relevant, right?

**Comment by itsjeyd** [comment]
@xitij2000 When you get a minute could you please post an update here about when you're planning to get back to this PR?

**Comment by xitij2000** [comment]
> @xitij2000 When you get a minute could you please post an update here about when you're planning to get back to this PR?

This and all the other PRs RE: design tokens are all based on an alpha version of paragon, so they are mainly for testing the MFE with design tokens. They can be updated when the version of paragon with design tokens is released, and potentially merged whent that happens.

**Comment by itsjeyd** [comment]
Thanks @xitij2000, I'll mark this PR as blocked on other work shortly.

**Comment by itsjeyd** [comment]
@xitij2000 Just checking in:

> This and all the other PRs RE: design tokens ... can be updated when the version of paragon with design tokens is released, ...

Do you have an update on when that might happen?

**Comment by xitij2000** [comment]
> @xitij2000 Just checking in:
> 
> > This and all the other PRs RE: design tokens ... can be updated when the version of paragon with design tokens is released, ...
> 
> Do you have an update on when that might happen?

Not really. Since the budget for this epic is small I'll close this for now and come back to it when the foundations are closer to complete.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1183&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-09-12+12:07&entry.1917517419=2024-01-16+15:35&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1183&entry.1484655318=https://github.com/xitij2000&entry.752974735=2023-09-12+12:07&entry.1917517419=2024-01-16+15:35&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
