### PR TITLE
[FC-0014] update frontend-platform version to v4.2.0

### PR DESCRIPTION
**Pull request by UvgenGen**
### Description

Updated frontend-platform version with GA4 implementation.
[FC-0014 - Google Analytics 4 Upgrade](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3668312128/FC-0014+-+Google+Analytics+4+Upgrade)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UvgenGen!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @UvgenGen, thank you for your contribution! Please let us know when it is ready for review.

**Comment by UvgenGen** [comment]
@itsjeyd Hi! Now this PR is ready for review)

**Review by arbrandes — APPROVED** [review]
I've tested this and it works just as well as master.  Approved.

@openedx/content-aurora, care to give a thumbs up/down?  I'd like to merge this some time tomorrow (Friday, Apr. 28).

**Comment by bmtcril** [comment]
@openedx/content-aurora hi all, just a heads up that we'll be merging this today if we don't hear back that you'd like to review!

**Comment by openedx-webhooks** [comment]
@UvgenGen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1102&entry.1484655318=https://github.com/UvgenGen&entry.752974735=2023-04-21+10:37&entry.1917517419=2023-05-02+17:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
