### PR TITLE
TNL-7126 BD-29 Visual Updates to Learning Sequence

### PR DESCRIPTION
**Pull request by pcockwell**
This PR updates some minor visual issues with the Learning Sequence:
- Changing `fa-film` icon to `fa-video`
- Adding `react-helmet` to update the page title

**JIRA tickets**:
- [OSPR-4725](https://openedx.atlassian.net/browse/OSPR-4725)
- [TNL-7126](https://openedx.atlassian.net/browse/TNL-7126)
- BD-29

**Dependencies**: None

**Screenshots**:
`fa-video` icon:
faVideoIcon

Title Change:
titleChange

**Merge deadline**: None

**Testing instructions**:

1. Pull the `open-craft:patrick/BB-2569-tnl-7126-minor-visual-updates-to-learner-sequen` branch locally and setup your local LMS.
2. Run `npm install && npm start` in your `frontend-app-learning` folder
3. Login to Studio and edit the demo course to add a new video unit.
4. Navigate to the video unit on your new learning sequence experience
5. Observe the unit icon, and title changes

**Author notes and concerns**:

1. There may be further changes for the sequence bar if needed
2. Initially, a `CourseLicense` component was added to display licensing, but due to the metadata api not containing the necessary information to display the course licensing, this has been removed from this PR.

**Reviewers**
- [ ] @xitij2000
- [x] @edx/teaching-and-learning

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pcockwell! I've created [OSPR-4725](https://openedx.atlassian.net/browse/OSPR-4725) to keep track of it in JIRA, where we prioritize reviews.  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Review by davidjoy — APPROVED** [review]
Looks great!

**Comment by lgp171188** [comment]
@pcockwell, I reviewed the changes and found that the changes for the below requirement are not there in this PR.

> Update height of sequence bar to emulate current bar (new one has 20% or so smaller height) 

Can you check and fix this issue as well?

The `package-lock.json` file has some conflicts. Can you check and resolve those as well?

Other than these 2 concerns, the changes in the PR look good to me. I will check and approve the PR once these are addressed.

**Comment by pcockwell** [comment]
> @pcockwell, I reviewed the changes and found that the changes for the below requirement are not there in this PR.
> 
> > Update height of sequence bar to emulate current bar (new one has 20% or so smaller height)

Per the [discussion on TNL-7126](https://openedx.atlassian.net/browse/TNL-7126?focusedCommentId=465287), that requirement is no longer needed.

> The package-lock.json file has some conflicts.

Will look into this now

**Comment by pcockwell** [comment]
@lgp171188 The `package-lock.json` conflicts are now fixed

**Review by lgp171188 — APPROVED** [review]
:+1: 
- [x] I tested the changes in this PR and verified that they work as expected.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] ~~Includes documentation~~

**Comment by pcockwell** [comment]
I think this is ready for a review from @edx/teaching-and-learning.

**Comment by davidjoy** [comment]
Already reviewed. 👍

**Comment by openedx-webhooks** [comment]
@pcockwell 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/88&entry.1484655318=https://github.com/pcockwell&entry.752974735=2020-06-18+04:28&entry.1917517419=2020-06-23+20:09&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
