### PR TITLE
feat!: remove Transifex calls for FC-0012

### PR DESCRIPTION
**Pull request by OmarIthawi**
## Breaking change!

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

## Changes

 - Removes all direct use of `tx pull` and `tx push` commands from the micro-frontend in favor
of the [`atlas pull`](https://github.com/openedx/openedx-atlas/) command.
 - Remove source and language translations from the repositories, hence no `.json` files will be committed into the repos. 
 - `src/i18n/index.js` should export and empty array so the `make pull_translations` override it with the dynamic list of languages.
 - Remove the experimental `OPENEDX_ATLAS_PULL` flag to make `atlas pull` the default. 
 - Remove all Transifex related `Makefile` targets and other files.

Merge timeline
-----------------------

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

Keep this pull request as a draft to prevent accidental merge.

### Pre-merge checklist

 - [ ] https://github.com/openedx/wg-translations/issues/20 is approved

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey @OmarIthawi, it looks like this PR is part of FC-0012. It would probably make sense to update the title accordingly? 🙂

**Comment by OmarIthawi** [comment]
Thanks for your review @itsjeyd. I've seen you requesting this a couple of times already, so I'd like to know if this is a new requirements?

So far we've been adding the keyword `FC-0012` and `OEP-58` to the pull request _description_, so it's searcheable.

We use this GitHub pull request query so to find all related pull requests:

 - All FC-0012/OEP-58 pull requests: https://github.com/pulls?q=OEP-58+FC-0012+is%3Aopen+is%3Apr

So I think it makes sense to keep the pull request title intact, but I'd like to hear from you as well.

**Comment by itsjeyd** [comment]
@OmarIthawi Thanks for the quick reply! It definitely makes sense to mention these keywords in the PR description. I mainly suggested to add the FC-0012 identifier to the title because @sarina had mentioned it [here](https://github.com/openedx/openedx-translations/pull/146#issuecomment-1516307485). I don't know if it's a hard requirement, though 🙂 

From the perspective of [OSPR management](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#Current-OSPR-Project-Managers) (which @mphilbrick211 and I are responsible for), what I will say is that having `FC` identifiers in PR titles makes it a bit easier to distinguish them from "regular" contributions. And that is helpful because `FC` PRs sometimes have different reviewers than regular PRs, and Michelle and I need to take that into account when pinging people for engineering review.

**Comment by OmarIthawi** [comment]
Makes sense @itsjeyd. We'll add it for new PRs.

**Comment by OmarIthawi** [comment]
We've duplicated our work 😓, my bad for making a task for the learning app again for my colleague.

Closing in favor of https://github.com/openedx/frontend-app-learning/pull/1198

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1186&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-09-18+11:10&entry.1917517419=2023-10-18+12:18&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
