### PR TITLE
[FC-0056] Course outline sidebar

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**Settings**

```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: ts-develop
```

### Description
This pull request adds an important feature to our platform: displaying a navigation sidebar within a given course.

### Design
https://www.figma.com/file/gew5tORDX4Q7wxOS8vjqZu/side-nav-OEX?type=design&node-id=318-3234&mode=design&t=rBe1ToNYP8RY6QOp-0

image

### Testing instructions
1. Run master devstack.
2. Start platform make dev.up.lms+cms+frontend-app-course-authoring and make checkout on this branch.
3. Go to Course Unit page from the Course Outline page.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey @jmakowski1123, since this is for an [FC project](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4063690758/FC-0056+-+Implement+Sidebar+Navigation) with status In Development, can we consider it approved from the product perspective?

Same question for other PRs related to the FC-0056 project.

CC @mphilbrick211 @crathbun428

**Comment by mphilbrick211** [comment]
> Hey @jmakowski1123, since this is for an [FC project](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4063690758/FC-0056+-+Implement+Sidebar+Navigation) with status In Development, can we consider it approved from the product perspective?
> 
> Same question for other PRs related to the FC-0056 project.
> 
> CC @mphilbrick211 @crathbun428

@jmakowski1123 just following up on this :)

**Comment by crathbun428** [comment]
@mphilbrick211 - If this pull request just represents the Phase 1 portion of the project, which has been tested, then yes, this has been approved by Product. The Phase 2 of the FC has yet to be tested by product. 

@GlugovGrGlib - does this pull request just represent the Phase 1 portion of the project?

**Comment by GlugovGrGlib** [comment]
> does this pull request just represent the Phase 1 portion of the project?

@crathbun428 yes, all FC-0056 PR, that are currently opened to openedx repositories are part of the phase 1

**Comment by crathbun428** [comment]
@GlugovGrGlib - Excellent - thank you for confirming.

@mphilbrick211 - We can consider this approved by product. Please let me know if you have any follow-up questions!

**Comment by itsjeyd** [comment]
Thanks @crathbun428 @GlugovGrGlib @mphilbrick211 for sorting this out.

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1342&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2024-04-01+15:40&entry.1917517419=2024-04-26+09:18&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ihor-romaniuk** [comment]
The main PR about the course outline sidebar functionality https://github.com/openedx/frontend-app-learning/pull/1349

**Pull request closed without merging**
