### PR TITLE
fix: alert.end.long should be alert.start.long

### PR DESCRIPTION
**Pull request by sambapete**
## Description

In src/alerts/course-start-alert/CourseStartAlert.jsx, learning.outline.alert.end.long should really be learning.outline.alert.start.long. It refers to a course starting in a date in the future, not a course with an end in the future.

The learning.outline.alert.start.long id does not exist. The code refers to learning.outline.alert.end.long on that line of code but logically it should really be learning.outline.alert.start.long used instead of learning.outline.alert.end.long.

learning.outline.alert.start.long should also be added to the translations files.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @sambapete!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by rediris — APPROVED** [review]

**Review by kdmccormick — COMMENTED** [review]
Nice fix.

I think the next message ID should be changed in the same way: `learning.outline.alert.end.calendar` -> `learning.outline.alert.start.calendar`. Could you make the same fix there?

**Comment by sambapete** [comment]
> Nice fix.
> 
> I think the next message ID should be changed in the same way: `learning.outline.alert.end.calendar` -> `learning.outline.alert.start.calendar`. Could you make the same fix there?

I definitely missed that one. You're right. It makes more sense too. Thanks. Done.

**Comment by sambapete** [comment]
Problem with some following PRs. Will close this one and open a new one.

**Comment by openedx-webhooks** [comment]
@sambapete Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1167&entry.1484655318=https://github.com/sambapete&entry.752974735=2023-08-22+19:12&entry.1917517419=2023-08-28+17:29&entry.2133058324=No) so we can improve your experience in the future.

**Comment by kdmccormick** [comment]
New PR: https://github.com/openedx/frontend-app-learning/pull/1173

**Pull request closed without merging**
