### PR TITLE
feat: add eslint role for no message description

### PR DESCRIPTION
**Pull request by ghassanmas**
This uses an eslint role for getting strings with no
  descriptions, this for demonstration purpose and can be used
  for checking other MFEs or JS/React base repos

  Ref: openedx/wg-translations/issues/5
  
  **This PR checks should fail**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey there @ghassanmas, thank you for this contribution! Please let us know when it is ready for review.

**Comment by brian-smith-tcril** [comment]
Thank you so much for making this example PR! I think this makes sense to have org wide, would you mind making a PR to https://github.com/openedx/frontend-build updating https://github.com/openedx/frontend-build/blob/master/.eslintrc.js?

I think a PR there would be a great place for the discussion around this to happen.

**Comment by itsjeyd** [comment]
Hi @ghassanmas @brian-smith-tcril, this PR hasn't seen any activity in a while so I wanted to check in and see if we should keep it open?

**Comment by itsjeyd** [comment]
Hi @ghassanmas, just a quick update that we're closing this PR now because it's become stale. Feel free to reopen if/when you have time to come back to this work :)

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1143&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-07-19+16:16&entry.1917517419=2023-09-26+07:00&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1143&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-07-19+16:16&entry.1917517419=2023-09-26+07:00&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
