### PR TITLE
Change design of tabs

### PR DESCRIPTION
**Pull request by junedkhatri31**
Improved course tabs and unit tabs design. Implemented designs with Google apps reference.

Changed following things in both tabs

- Background color light theme
- Text color theme color
- Removed underline
- Hover color light gray

Visuals
Screenshot 2020-11-15 at 1 40 10 PM
Screenshot 2020-11-15 at 1 40 23 PM

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @junedkhatri31! I've created [OSPR-5132](https://openedx.atlassian.net/browse/OSPR-5132) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@junedkhatri31 Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by junedkhatri31** [comment]
@natabene sure I will do it. Where do I have to send it after signing?

**Comment by natabene** [comment]
@junedkhatri31 Please send it to legal@edx.org

**Comment by junedkhatri31** [comment]
@natabene I have sent the signed agreement. Please let me know further steps.

**Comment by natabene** [comment]
@junedkhatri31 Thank you for sending the agreement. Please give our legal team a few days to process. I will post here once you are all set.

**Comment by natabene** [comment]
@junedkhatri31  Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
jenkins run all

**Comment by natabene** [comment]
@marcotuts Can you give this a look when you have a chance?

**Comment by natabene** [comment]
@nedbat Could you help me to kick off Travis here?

**Comment by marcotuts** [comment]
Hello! Thanks for the contribution here. ￼

I've flagged this to @abutterworth as an FYI for consideration as a model for the open edX theme but for our platform default we will likely keep the current tab layout. 

Paragon makes theming easier now to override this, and if you have questions about that we can link you to the right place to customize that for your instance.

**Comment by openedx-webhooks** [comment]
@junedkhatri31 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/272&entry.1484655318=https://github.com/junedkhatri31&entry.752974735=2020-11-15+08:22&entry.1917517419=2021-02-26+19:00&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
