### PR TITLE
WIP: Don't show Order History link if URL not provided.

### PR DESCRIPTION
**Pull request by mtyaka**
TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-6156](https://openedx.atlassian.net/browse/OSPR-6156) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@mtyaka Thank you for your contribution, please let me know once this is ready.

**Comment by mtyaka** [comment]
Closing this since it's no longer relevant as of https://github.com/edx/frontend-app-learning/pull/781

**Comment by openedx-webhooks** [comment]
@mtyaka Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/700&entry.1484655318=https://github.com/mtyaka&entry.752974735=2021-10-21+08:12&entry.1917517419=2021-12-23+08:10&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
