### PR TITLE
[BB-933] Change `contentType` with `icon` for unit buttons

### PR DESCRIPTION
**Pull request by Agrendalath**
This PR is a part of edx/edx-platform#21433. As the learning UI is being moved to MFE, we ported the LMS frontend changes here.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-4621](https://openedx.atlassian.net/browse/OSPR-4621) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@Agrendalath Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by natabene** [comment]
@Agrendalath Just curious if you are still interested in pursuing this.

**Comment by Agrendalath** [comment]
@natabene, sorry for missing your question. That's correct, but we're planning to get back to this after merging  edx/edx-platform#21433. Converting this to a draft for now.

**Comment by Agrendalath** [comment]
@natabene, with the reworked approach we don't need this anymore. Closing.

**Comment by openedx-webhooks** [comment]
@Agrendalath Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/77&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2020-06-01+21:14&entry.1917517419=2021-03-25+13:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
