### PR TITLE
fix: pass originalUserIsStaff to SequenceExamWrapper

### PR DESCRIPTION
**Pull request by bseverino**
[MST-944](https://openedx.atlassian.net/browse/MST-944)

Pass this value to determine whether the user is staff masquerading as a learner.

Related PRs:
https://github.com/edx/edx-platform/pull/28458
https://github.com/edx/frontend-lib-special-exams/pull/40

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by schenedx** [comment]
This PR should also bump the version of the frontend-lib-special-exams library to 1.13.0, right?

**Comment by bseverino** [comment]
> This PR should also bump the version of the frontend-lib-special-exams library to 1.13.0, right?

Yeah, once the other PR is merged I'll update this one

**Review by mikix — APPROVED** [review]

**Review by cdeery — APPROVED** [review]
Looks good to me

**Review by zacharis278 — APPROVED** [review]

**Pull request merged**
