### PR TITLE
 feat: add experimental feature for direct XBlock rendering [FC-0035]

### PR DESCRIPTION
**Pull request by Agrendalath**
## Description

This PR ports the XBlock iframe wrapper, originally designed for the Library Authoring MFE. Instead of embedding the LMS view in an iframe, this approach queries XBlock v2 API to get the fragment's HTML and resources, then it assembles a <head> tag with all necessary assets and then finally puts ready HTML markup in an iframe.

This is an experimental approach that will need lots of improvements to reach the feature parity with the old view. Some known bugs/missing features:
- The "Staff Info" and "Submission History" buttons are missing.
- Video transcriptions are missing.
- ORA2 does not work.
- The `.inline-discussion-thread-container` is not rendered in Discussion XBlocks. As they had been replaced by the Discussions sidebar, fixing this might not be necessary.
- XBlock handlers (e.g., submitting the solution in CAPA blocks) do not work inside the Library Content Block. Given that these blocks are meant to be replaced by the `openedx-learning`, fixing this might not be necessary.

## Supporting information

Required backend changes: https://github.com/openedx/edx-platform/pull/34161.

## Testing instructions

1. Use the branch from https://github.com/openedx/edx-platform/pull/34161 for edx-platform.
2. Checkout the branch from this PR.
3. Set `RENDER_XBLOCKS_EXPERIMENTAL=true` in `frontend-app-learning/.env.private`.
4. (Optionally) Set `RENDER_XBLOCKS_DEFAULT=false` in `frontend-app-learning/.env.private`.
5. Go through a course.

## Deadline

"None"

## Other information

* https://github.com/aximcollaborative/funded-contributions/issues/15
* _Private-ref: [BB-7872](https://tasks.opencraft.com/browse/BB-7872)_

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by navinkarkera — COMMENTED** [review]
@Agrendalath This is really interesting. I followed your instructions and tested this locally. The new way seems to be a bit slower as compared to current implementation, if I am not wrong this should improve when xblocks do not use global dependencies.

---
I also noticed some difference in style and missing styles and icons like below:
Screenshot 2024-02-06 at 12-38-14 Basic Assessment Tools Open edX Demo Course edX

---

`Download handout` button in videos is defaulting to current domain (MFE domain) instead of LMS, so it is not working.

This is probably a general issue where if you link any unit using the relative path (jump-id) for example: `/jump_to_id/dacc88e550bd48db93899979bff1b086`, it defaults to current domain and fails. The current implementation goes to LMS domain by default.

---

Mathjax fails to render after submit when you have a simple number as input, for example:
image
Raises `Uncaught SyntaxError: expected expression, got '<' formula_equation_preview.js:1`

---
We probably need to write some tests or ignore the file for now to make sure we don't cause problems for other PRs (coverage failure).

**Comment by Agrendalath** [comment]
@navinkarkera,
> The new way seems to be a bit slower as compared to current implementation, if I am not wrong this should improve when xblocks do not use global dependencies.

Eventually - yes. Once we implement the support for `learn_view`, we will no longer need to load all dependencies. However, the `student_view` will be a bit slower since we need to pull the dependencies separately for each XBlock.

The problems you noted seem to be happening in the original version (the one in the `frontend-app-library-authoring`), so fixing them will be addressed in a follow-up project. We will also need to make some changes to the `ReplaceURLService`, which will also be addressed later.

**Review by navinkarkera — APPROVED** [review]
@Agrendalath Got it. Looks good to me.

:+1:
- [x] I tested this: (played around with xblocks locally)
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~

**Comment by Agrendalath** [comment]
@brian-smith-tcril, would you be able to review this as the CC?

**Comment by arbrandes** [comment]
I think @ormsbee will want to take a look at the whole thing as part of FC-0035 - particularly the backend PR - first.  I can come back here once the concept is approved.

**Comment by itsjeyd** [comment]
OSPR management note: As of today this PR is still blocked on https://github.com/openedx/edx-platform/pull/34161 ([ref](https://github.com/openedx/edx-platform/pull/34161#issuecomment-2032578585)).

**Comment by Agrendalath** [comment]
Closing for now, as mentioned in https://github.com/openedx/edx-platform/pull/34161#issuecomment-2118246779.

**Comment by openedx-webhooks** [comment]
@Agrendalath Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1281&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2024-02-01+00:04&entry.1917517419=2024-05-17+19:28&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
