### PR TITLE
fix: rewrite calcualtor tips to reflect the supported features

### LINKED ISSUE #820: Rewrite calculator supported constants
So in calcualtor examples tables in list some constants that are no longer supported: 

https://github.com/openedx/frontend-app-learning/blob/61f0ce2023cc2332a1e1fe5dd3dae035074b6e46/src/courseware/course/content-tools/calculator/Calculator.jsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L257-L266 

In calcuator V3 some constants are removed, hence: https://github.com/openedx/openedx-calc/commit/5e75af6ce444ce4933ef145bb4f57d64eaeb6433 

Also this might lead to [affiex tip](https://github.com/openedx/frontend-app-learning/blob/61f0ce2023cc2332a1e1fe5dd3dae035074b6e46/src/courseware/course/content-tools/calculator/Calculator.jsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L140-L145) to not work as expected, so may be this also need to be removed:

### PR DESCRIPTION
**Pull request by ghassanmas**
Fixes #820
  - Removing constants that are no longer supported
  - Removing suffixes that are no longer supported
  
  @pdpinch Following our conversation, here is the PR.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas! I've created [OSPR-6457](https://openedx.atlassian.net/browse/OSPR-6457) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ghassanmas Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by ghassanmas** [comment]
It’s ready for review.

**Review by jmyatt — APPROVED** [review]
LGTM

**Comment by openedx-webhooks** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/825&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-02-15+14:18&entry.1917517419=2022-02-17+16:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
