### PR TITLE
fix: show site name instead of edX

### PR DESCRIPTION
**Pull request by dcoa**
This PR fixes some hardcoded "edX" reference and use config().SITE_NAME instead.

Changes are in the NewUserCourseHomeTourModal and SupportMissionBullet components. 

**Before**
upselling-before
modal-newuser-before
**After**
learning-upselling-bullet
new-user-modal

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dcoa! I've created [OSPR-6678](https://openedx.atlassian.net/browse/OSPR-6678) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by regisb — APPROVED** [review]
Looking good! In the BTR working group we are eager to backport this change in the open-release/nutmeg.master branch.

**Comment by natabene** [comment]
@dcoa Thank you for your contribution. Let's see how tests turn out.

**Comment by natabene** [comment]
Lining this up for our review.

**Review by BbrSofiane — APPROVED** [review]
Looks good to me!

**Comment by openedx-webhooks** [comment]
@dcoa 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/945&entry.1484655318=https://github.com/dcoa&entry.752974735=2022-05-12+20:40&entry.1917517419=2022-05-18+11:23&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
