### PR TITLE
chore: translations updated

### PR DESCRIPTION
**Pull request by CodeWithEmad**
Translations have been added to this pull request as of August 7th, 2023.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hey @CodeWithEmad, thanks for the contribution! Please let us know when the changes are ready for review.

**Comment by CodeWithEmad** [comment]
Hey @itsjeyd 
It's ready for review. I've updated some translations in transifex and wanted the master to have the latest translations.

**Comment by itsjeyd** [comment]
Thanks @CodeWithEmad.

@mattcarter This is ready for Aurora.

**Comment by itsjeyd** [comment]
@mattcarter A friendly reminder about this PR -- could you please help us get it scheduled for engineering review by Aurora?

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
@CodeWithEmad thanks for you contribution. 

Sorry for the late review but I'm going to ask for a big change:

Instead of updating the messages manually, please translate in Transifex in case you haven't.

Then add Persian to the following list:

https://github.com/openedx/frontend-app-learning/blob/2ae033160f5653c2705e15df9661633d7adb51ee/Makefile#L2C52-L2C52

Then the edX Transifex bot will automatically add it to the application on the next sync event (mostly next day).

This applies to most frontend-apps (MFEs).

**Comment by CodeWithEmad** [comment]
Thanks @OmarIthawi. I'll close this one since `fa_IR` is added before.

**Comment by openedx-webhooks** [comment]
@CodeWithEmad Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1151&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2023-08-07+11:25&entry.1917517419=2023-09-07+17:25&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@CodeWithEmad Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1151&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2023-08-07+11:25&entry.1917517419=2023-09-07+17:25&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
