### PR TITLE
docs: broken readme fixed

### LINKED ISSUE #1266: README file broken
Right now the title section has an extra `#` and caused the readme break.

### PR DESCRIPTION
**Pull request by CodeWithEmad**
This will fix a typo and the broken README page. 
Close #1266

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@CodeWithEmad Thank you for this contribution! It looks like the changes are ready for review, but please let me know if that's not the case.

**Comment by CodeWithEmad** [comment]
Yeah, it's not much, but will fix the broken README.

**Comment by itsjeyd** [comment]
@e0d This is a trivial fix, can we consider it eligible for CC review and merge?

**EDIT**: The first meeting of the Maintenance WG answered this question -- we can let CCs [take on Reviews and Merges that they can manage](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4031578215/2024-02-01+Meeting+notes#%E2%A4%B4-Decisions).

CC @mphilbrick211

**Comment by itsjeyd** [comment]
Hey @BbrSofiane, as a core contributor for frontend-app-learning, would you have time to give this a quick look and merge it? It's a trivial change so shouldn't take more than 5 mins to review.

**Comment by itsjeyd** [comment]
@BbrSofiane A friendly ping about my question above.

If you don't have bandwidth for reviewing PRs from this repo right now, no problem! Please just let me know so I can start looking for other reviewers.

**Review by jristau1984 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1264&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2023-12-31+09:41&entry.1917517419=2024-03-03+12:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
