### PR TITLE
fix: first section celebration

### PR DESCRIPTION
**Pull request by dyudyunov**
fix: first section celebration

Fix the first section celebration modal showing logic.

On Nutmeg+ it's shown only after the page reload or after going directly
to the second section from the course home. Going through the course
with the Next/Previous buttons has no effect (which worked on Maple).

Notes:
- the weekly goal has the same showing logic, but I assume that is
correct behavior so no changes are added for it in this commit.
- showing a celebration modal for the first section completion when
going directly to the first unit of the second section seems to be a bug
(reproduces on Maple too)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
this is a backport of https://github.com/openedx/frontend-app-learning/pull/976

**Comment by natabene** [comment]
@dyudyunov Thank you for the contribution, looks like this is ready.

**Comment by dyudyunov** [comment]
> @dyudyunov Thank you for the contribution, looks like this is ready.

yes 👍

**Comment by dyudyunov** [comment]
Hi @natabene 
Can you tell if this one was planned for review?

**Comment by natabene** [comment]
@dyudyunov It is lined up but I don't know when team will have bandwidth for this.

**Comment by ProductRyan** [comment]
internal tracking link:
https://2u-internal.atlassian.net/browse/AU-946

**Review by muselesscreator — COMMENTED** [review]
Please add tests for these new behaviors.

**Review by muselesscreator — CHANGES_REQUESTED** [review]
Please add tests for the new behaviors

**Comment by itsjeyd** [comment]
@dyudyunov Please let us know when this is ready for review again. I'll mark it as `waiting-on-author` in the meantime, like I [just did](https://github.com/openedx/frontend-app-learning/pull/976#issuecomment-1352849146) for #976.

**Comment by dyudyunov** [comment]
hi @itsjeyd @muselesscreator 

please, run checkers and review

**Comment by itsjeyd** [comment]
@muselesscreator A quick heads-up that this is now ready for review, [too](https://github.com/openedx/frontend-app-learning/pull/976#issuecomment-1362542455). (Checks ran successfully.)

**Comment by itsjeyd** [comment]
Hey @muselesscreator, a friendly nudge about reviewing this PR.

**Comment by itsjeyd** [comment]
@muselesscreator A quick heads-up that this PR was tagged for product review so it might actually make sense to hold off on technical review for now.

CC @jmakowski1123

**Comment by itsjeyd** [comment]
@ProductRyan Once product review for the main PR (https://github.com/openedx/frontend-app-learning/pull/976) is done, could you please approve this PR (Nutmeg backport) and https://github.com/openedx/frontend-app-learning/pull/1044 (Olive backport) as well?

@dyudyunov We'll move forward with engineering review after getting 👍 from product here.

**Comment by itsjeyd** [comment]
@ProductRyan I'll consider this backport [approved](https://github.com/openedx/frontend-app-learning/pull/976#issuecomment-1414245124) from the product perspective, but let me know if you have any objections.

**Comment by itsjeyd** [comment]
@dyudyunov Once #976 gets a green [build](https://github.com/openedx/frontend-app-learning/pull/976#issuecomment-1422321428), could you make sure that this PR is up-to-date with all the latest changes from #976?

Then we'll be able to give this to the engineering team again for a final look.

CC @muselesscreator

**Review by leangseu-edx — APPROVED** [review]
LGTM 👍

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/977&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2022-09-14+15:15&entry.1917517419=2023-02-14+20:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
