### PR TITLE
chore: update sidebar logic

### PR DESCRIPTION
**Pull request by leangseu-edx**
https://2u-internal.atlassian.net/browse/AU-1552

1. If a course has an upgrade option, it will automatically open whenever the page is refreshed. 
2. If a course has already been upgraded, it will behave as it used to
    1. Open discussion board when available
    2. Else don't open the sidebar

### **After Fix**    
**Desktop**
Screenshot 2023-11-22 at 12 41 08 PM
**Mobile**
Screenshot 2023-11-22 at 12 40 16 PM

### CODE REVIEW

**Comment by ayub02** [comment]
@leangseu-edx Does this PR also resolve the issue where notifications sidebar would open but no notifications were present in the sidebar?

[Not a blocker for this PR] Also, can you please share any details on following:

1. On what course units, is a notification intended to appear? Afaik, it didn't appear on all units before march 2023. 
2. How can we create a notification for testing?

cc: @awais-ansari @asadazam93 @mattcarter

**Comment by awais-ansari** [comment]
@leangseu-edx This change will show the notification tray on mobile full-screen in every unit. It will be disturbing for mobile users to close the notification tray first in every unit to see the content. Is this expected behavior? 
Other than this change is LGTM.

**Comment by awais-ansari** [comment]
> @leangseu-edx Does this PR also resolve the issue where notifications sidebar would open but no notifications were present in the sidebar?
> 
> [Not a blocker for this PR] Also, can you please share any details on following:
> 
> 1. On what course units, is a notification intended to appear? Afaik, it didn't appear on all units before march 2023.
> 2. How can we create a notification for testing?
> 
> cc: @awais-ansari @asadazam93 @mattcarter

@ayub02 Notification try will be visible on every unit, if the course is not upgraded.

**Comment by leangseu-edx** [comment]
> @leangseu-edx This change will show the notification tray on mobile full-screen in every unit. It will be disturbing for mobile users to close the notification tray first in every unit to see the content. Is this expected behavior? Other than this change is LGTM.

This is also the current behavior for discussion. I also agree that it shouldn't do that in mobile view but I would rather keep the behavior consistent for now.

**Review by mattcarter — APPROVED** [review]
approved

**Pull request merged**
