### PR TITLE
feat: upgraded to node v18, added .nvmrc and updated workflows

### PR DESCRIPTION
**Pull request by BilalQamar95**
## Ticket
[Upgrade Node Js from 16 to 18](https://github.com/openedx/frontend-app-learning/issues/1085)

## Description
- Added support for node v18, updated .nvmrc and workflows. 
- Upgraded `frontend-build` to v12.8

## edx-internal PR
https://github.com/edx/edx-internal/pull/8336
This needs to be merged together.

### CODE REVIEW

**Comment by ghassanmas** [comment]
Hello, 

Would it be possible to upgrade frontend-build in this PR to at least 12.8.0 (similar to this openedx/frontend-app-course-authoring/pull/464 ) hence from 12.7.0 frontend-build is upgraded to use node 18.  I just think doing it through this PR would be more efficient and I am happy to help if there are any blockers to this PR.   

For more context:  https://github.com/openedx/frontend-app-learning/pull/1047#issuecomment-1510000081 


CC: @itsjeyd

**Review by jansenk — APPROVED** [review]
Makes sense to me

**Comment by ghassanmas** [comment]
Hey, just a note about frontend-build in the comment above, would that befeasible to do this PR?

**Comment by BilalQamar95** [comment]
> Hey, just a note about frontend-build in the comment above, would that befeasible to do this PR?

Sure @ghassanmas, I have updated `frontend-build` version to 12.8

**Comment by arbrandes** [comment]
I temporarily removed `tests (16)` from the branch protection rules so we can actually merge this, but we still need a package-lock regen to fix the conflicts.

**Comment by arbrandes** [comment]
Tests re-enabled.

**Pull request merged**
