### PR TITLE
feat: upgrade react router to v6

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
## Ticket
[React Router Upgrade to v6](https://github.com/openedx/platform-roadmap/issues/276).

## Description
This PR upgrades React Router from `v5` to `v6`.

### CODE REVIEW

**Comment by arbrandes** [comment]
@Syed-Ali-Abbas-Zaidi, I'd love to help push this forward.  Do you mind resolving conflicts?  Also, is there a particular reason the PR is still a draft?

Thanks!

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
This PR is currently blocked due to [React v17 upgrade](https://github.com/openedx/frontend-app-learning/pull/1127) that is the reason I have marked it as Draft.

**Comment by arbrandes** [comment]
Looks like React v17 was merged, congrats!  Can we move this one forward, now?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> Looks like React v17 was merged, congrats! Can we move this one forward, now?

Yes, I have already notified the owning squad (aurora) they are currently working on testing these changes locally. Once testing is done this PR will be good to go.

**Review by mattcarter — APPROVED** [review]
approved

**Pull request merged**
