### PR TITLE
fix: add support for legacy theme static for the 'LmsHtmlFragment'

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**Description:**
When we apply branding by the `edx-brand` template, we can't affect to styles of the iframe content and we get default platform styles (not theme styles).
When we will use `LEGACY_THEME_NAME` we will be able to use theme legacy styles for the iframe content.

image

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk! I've created [OSPR-6338](https://openedx.atlassian.net/browse/OSPR-6338) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ihor-romaniuk Thank you for your contribution. Is this ready for our review?

**Comment by ihor-romaniuk** [comment]
@natabene Yes, it's ready for review. Thanks.

**Comment by cdeery** [comment]
I am not an expert in iframes, but does this work in practice? Will adding the style in the parent affect the iframe?
Have you tested this with a css file and verified it?

**Comment by cdeery** [comment]
Do you have a candidate css file to use for this styling?

**Comment by ihor-romaniuk** [comment]
@cdeery I think that we should not use any CSS files by default and use it as an additional config for theming.

**Review by cdeery — APPROVED** [review]
I get it. The default css is used unless the variable is set.
Thanks.

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/785&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2021-12-22+10:32&entry.1917517419=2022-01-14+16:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
