### PR TITLE
[DRAFT] feat: add support to paragon design tokens

### PR DESCRIPTION
**Pull request by ghassanmas**
This PR purpose is to test/demo parago design tokens simliar
  to this one for the profile openedx/frontend-app-profile/pull/764

  it override the following depns as seen in package.json

  - paragon alpha
  - openedx/frontend-build/pull/365
  - openedx/frontend-platform/pull/440
  - openedx/frontend-component-header/pull/351
  - openedx/frontend-component-footer/pull/303

 Conclousion so far:

 - There is an extra library that learning depends on which needs to support paragon; `frontend-lib-learning-assistant` and also `frontend-lib-special-exams`

 - It would be great to have a gudie or a document to look at, while doing the conversion that would **map variable from who it was used/named before to the name in design tokens**

 - I was stuck in the end with compliation error, that wepack couldn't find `Modal` exported from paragon.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Thank you for this contribution @ghassanmas! Let us know when the changes are ready for review.

**Comment by itsjeyd** [comment]
Hi @ghassanmas! Just a quick update that we're closing this PR for now because it seems to be stale. You can of course reopen this pull request, or open a new one, when you have time to come back to this work.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1203&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-10-06+08:58&entry.1917517419=2023-11-17+09:14&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1203&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-10-06+08:58&entry.1917517419=2023-11-17+09:14&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ghassanmas** [comment]
@itsjeyd this was for demonstration just like this https://github.com/openedx/frontend-app-profile/pull/764

**Pull request closed without merging**
