### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: it_IT,pt_PT,de_DE

@feanil   
@natabene  

When executing the make pull_translations command, some files are automatically modified.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hey @Yoiber071, thank you for your contribution! We'll get tests enabled for the changes next. CC @e0d 

Once they are green we'll be ready to start the review process.

**Comment by e0d** [comment]
@Yoiber071 looks like there are test failures.

**Comment by itsjeyd** [comment]
Hi @Yoiber071, a friendly reminder to fix failing tests here.

**Comment by felipemontoya** [comment]
Tests run.

-- testing if I could approve the workflows run

**Comment by Yoiber071** [comment]
Hi @itsjeyd, Sorry for the late response, I've fixed the lint failures, and is ready to be tested again.

**Comment by itsjeyd** [comment]
No worries @Yoiber071, and thanks for the update.

I'm marking this as ready for another test run. CC @e0d

**Comment by e0d** [comment]
@itsjeyd tests are passed, removing the label.

**Comment by itsjeyd** [comment]
Thanks @e0d!

That means this is ready for engineering review now.

@mattcarter Could you or someone from your team please have a look?

**Comment by itsjeyd** [comment]
Hi @Yoiber071, just a quick update about next steps for this PR: It might take a little while longer for engineering review to start but the current plan is to get it reviewed and merged before [Palm](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3552938822/Palm) branches are cut.

Thank you for your patience!

CC @mattcarter @hurtstotouchfire

**Review by leangseu-edx — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Yoiber071 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1063&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+17:22&entry.1917517419=2023-04-18+16:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
