### PR TITLE
fix: fix alignment in the streak celebration modal

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**Description:**
Fix alignment in the streak celebration modal. The reason for the error is the upgrade of the paragon library from version `16.14.9` to `19.14.1`.

**Current behaviour:** 
image

**Fixed behaviour:** 
fixed

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ihor-romaniuk Thank you for the contribution!

**Comment by itsjeyd** [comment]
@ihor-romaniuk Just to confirm: This PR is ready for review, right?

**Comment by ihor-romaniuk** [comment]
@itsjeyd Yes. It's ready for review. Thanks.

**Comment by ProductRyan** [comment]
@ihor-romaniuk thanks for this contribution. I'm going to get it reviewed by the engineering team.

**Comment by ihor-romaniuk** [comment]
@ProductRyan Perfect. Thanks in advance.

**Comment by ProductRyan** [comment]
Internal tracking link:
https://2u-internal.atlassian.net/browse/AU-938

**Review by muselesscreator — APPROVED** [review]
lgtm

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/974&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2022-09-12+15:32&entry.1917517419=2022-12-05+16:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
