### PR TITLE
fix: Use Link from router to fix path based routing issue

### PR DESCRIPTION
**Pull request by regisb**
Backport of: https://github.com/edx/frontend-app-learning/pull/777

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-6324](https://openedx.atlassian.net/browse/OSPR-6324) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by openedx-webhooks** [comment]
@jmbowman, @kdmccormick: thought you might like to know that regisb merged this pull request.

**Comment by openedx-webhooks** [comment]
@regisb 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/780&entry.1484655318=https://github.com/regisb&entry.752974735=2021-12-20+15:24&entry.1917517419=2021-12-20+15:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@regisb @BbrSofiane Thank you both.

**Pull request merged**
