### PR TITLE
fix: remove redundant form-control in masquerade user input

### PR DESCRIPTION
**Pull request by tecoholic**
## Description

This PR just removes a redundant class from the code. There are no UI changes in the master version as the same class is applied to twice. This was causing an issue in the previous versions which are using the `@edx/paragon` and `FormControl` in the `MasqueradeUserNameInput` (Ref: see https://github.com/open-craft/frontend-app-learning/pull/24).

Since master branch uses `@openedx/paragon` and `Input` in the `MasqueradeUserNameInput` component, the styles don't really cause any UI issues and it is just a minor improvement in code quality.

### Before

image

### After

image

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @tecoholic!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/2u-aurora`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by itsjeyd** [comment]
@tecoholic Is this waiting for OpenCraft internal review or did you want to send it straight to upstream review?

**Comment by tecoholic** [comment]
@itsjeyd I have pinged @farhaanbukhsh internally to take a look at this. However, I wasn't certain if he has CC access to this repo at that time. The [CC list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project) indicates there are no CCs from OpenCraft who have access.

This PR was a side effect of an internal ticket and, as such, doesn't fix anything. So, I would like to get an upstream review directly if possible.

**Comment by farhaanbukhsh** [comment]
Hey @tecoholic I am not a CC/maintainer for the repo :) from backstage I can see that [2u-aurora](https://backstage.openedx.org/catalog/default/group/2u-aurora) maintains it.

**Comment by itsjeyd** [comment]
@tecoholic Got it, I'll mark this as ready for review now.

@farhaanbukhsh @tecoholic The Aurora team is [stepping down](https://discuss.openedx.org/t/learning-mfe-looking-for-a-new-maintainer/13414) as maintainer and most likely won't be reviewing this PR.

@feanil @arbrandes @brian-smith-tcril Would one of you be able to help us get this tiny change over the line?

**Review by feanil — APPROVED** [review]
Change looks good and tested locally just fine.

**Comment by openedx-webhooks** [comment]
@tecoholic 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1416&entry.1484655318=https://github.com/tecoholic&entry.752974735=2024-07-05+09:54&entry.1917517419=2024-08-01+15:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by itsjeyd** [comment]
Thanks a lot @feanil.

**Pull request merged**
