### PR TITLE
fix: Replace WatchOutline with Notifications #1509

### PR DESCRIPTION
**Pull request by jciasenza**
[#1509](https://github.com/openedx/frontend-app-learning/issues/1509)

What changed?
Replace WathOutline icon with notifications
it looks more aesthetic

image

Screenshot from 2024-11-01 15-43-47

And Testing OK

If something needs to be modified, let me know, thank you!!!
Atte
Juan Carlos (Aulasneo)

Developer Checklist

Test suites passing
Documentation and test plan updated, if applicable
Received code-owner approving review

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jciasenza!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/committers-frontend-app-learning`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by itsjeyd** [comment]
@jciasenza Thank you for this contribution!

We have a green build here so I'm marking this PR as ready for review. (Let us know if you had plans to continue working on the changes before putting them up for review, though.)

**Comment by jciasenza** [comment]
[itsjeyd](https://github.com/itsjeyd) I think it would be ready so they can merge it

**Comment by bradenmacdonald** [comment]
@jciasenza Thank you for the contribution. @itsjeyd This looks great from my perspective but shouldn't we get a product +1 since it's a UX change?

**Comment by angonz** [comment]
> @jciasenza Thank you for the contribution. @itsjeyd This looks great from my perspective but shouldn't we get a product +1 since it's a UX change?

I asked Chelsea in the original issue to look at it.

**Comment by itsjeyd** [comment]
@bradenmacdonald @jciasenza Sounds good re: getting product approval.

**Comment by itsjeyd** [comment]
Hey @angonz and @jciasenza, any updates here? It looks like the conversation over on https://github.com/openedx/frontend-app-learning/issues/1509 has stalled.

**Comment by angonz** [comment]
it's strange, but in Sumac the notification icon is already a bell. 
image
Looks like somebody already did it without further approval... Can we close this?

**Comment by itsjeyd** [comment]
@angonz Sounds good to me :)

@jciasenza Any objections from your side?

**Comment by jciasenza** [comment]
No, it seems fine to me, I had taken the Issue of [aphilipharrell](https://github.com/aphilipharrell), but I didn't know it was already done for Sumac.

**Comment by itsjeyd** [comment]
@jciasenza No worries, and thank you for confirming. I'll close this now.

**Pull request closed without merging**
