### PR TITLE
Testiing Reduce css

### PR DESCRIPTION
**Pull request by ghassanmas**
This is opened only for testing purpose regarding openedx/frontend-build/pull/266

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by e0d** [comment]
@ghassanmas this is interesting work.  Should this be a draft PR?  It's helpful for us that PRs remain in a draft state until they are ready for review.

**Comment by ghassanmas** [comment]
@e0d initially I opened this PR to ease the testing of https://github.com/openedx/frontend-build/pull/266 
 If it get merged then I would need to update this PR to point the latest frontend-build as opposite to my git fork, but then that would require extra work because currently learning MFE is behind 2 version of frontend-build, where the new version of front-build require new/different eslint roles/version.

**Comment by itsjeyd** [comment]
label: core contributor

**Comment by itsjeyd** [comment]
Hey @ghassanmas, now that https://github.com/openedx/frontend-build/pull/266 has been merged (🎉), will you be picking up work on this PR again?

**Comment by itsjeyd** [comment]
@ghassanmas A friendly ping about my previous comment.

**Comment by ghassanmas** [comment]
@itsjeyd Sorry for the late reply. And thank you for the reminder. 
For the learning MFE to utilize the new feature it just need to use frontend-build version >12.8.0 [ref](https://github.com/openedx/frontend-build/releases/tag/v12.8.0). Which is not the case yet!

I can open a new PR to upgrade it but I suspect it will be relate to this PR #1084. So it's best _in terms of reducing friction, merge conflict...etc_ That if #1084 would also update front-build to at least 12.8.0, given  from version > 12.7.0 [ref](https://github.com/openedx/frontend-build/releases/tag/v12.7.0) frontend-build is upgraded to use node 18. Also that PR is already tracked to be included in Palm in openedx/wg-build-test-release/issues/261.   

Moving forward, I will close this PR, and I will comment on the referred PR #1084 to ask if it's possible to upgrade frontend-build, I will also check frontend-build version for other MFEs to ensure this feature is available for palm.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1047&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-01-18+16:05&entry.1917517419=2023-04-15+23:28&entry.2133058324=No) so we can improve your experience in the future.

**Comment by itsjeyd** [comment]
No worries, and thanks for the detailed update @ghassanmas! :)

**Pull request closed without merging**
