### PR TITLE
Feature: Persian language

### PR DESCRIPTION
**Pull request by CodeWithEmad**
Hello everyone
I'm glad to announce that we translated all openedx components in transifex to Persian and fa_IR is 100% translated and 100% reviewed.

in this PR, I've added:
new translations to `i18n/messages/fa_IR.json`,
`fa-ir` in messages in `src/i18n/index.js`,
and `fa_IR` code in `transifex_langs` variable in `Makefile`.

is there anything else I should do?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@CodeWithEmad Thank you for your contribution!

Hi @mattcarter! When you get a minute, could you please enable tests to run for this PR?

(I'm [assuming](https://github.com/openedx/frontend-app-learning/pull/978#issuecomment-1276731883) you're the right person to ping; if that's not the case please let me know and I will be happy to reach out to someone else.)

**Comment by itsjeyd** [comment]
@CodeWithEmad In case you run into any issues with tests, [this documentation](https://docs.openedx.org/en/latest/developers/references/running_pr_tests.html) might help you out.

**Comment by itsjeyd** [comment]
Hey @mattcarter, a friendly ping about my [earlier comment](https://github.com/openedx/frontend-app-learning/pull/989#issuecomment-1293246405). If we could get tests to run on this PR, that'd be great :)

**Comment by e0d** [comment]
@itsjeyd and @CodeWithEmad I don't think we can run the tests until the branch conflicts have been resolved.  Let me know when that's been done and I can run them.

**Comment by itsjeyd** [comment]
Will do, thanks @e0d.

**Comment by itsjeyd** [comment]
Hey @CodeWithEmad, a friendly reminder to resolve the branch conflicts mentioned [above](https://github.com/openedx/frontend-app-learning/pull/989#issuecomment-1361571189).

**Comment by CodeWithEmad** [comment]
Hi @itsjeyd
I don't know how I missed this. so sorry.
conflicts resolved.

**Comment by itsjeyd** [comment]
@CodeWithEmad No problem, and thank you for the update!

It looks like the tests have finished running now, and one of them failed. Could you please check it out? Once the build is green this PR will be ready for engineering review.

**Comment by CodeWithEmad** [comment]
Hi @itsjeyd. sure, I'll look into that.

**Comment by CodeWithEmad** [comment]
I think the `package-lock.json` was not updated successfully. can anybody approve running tests one more time?
@itsjeyd can you please return the `needs test run` badge?

**Comment by e0d** [comment]
@CodeWithEmad tests approved.

**Comment by itsjeyd** [comment]
@mattcarter This is ready for engineering review by Aurora.

**Comment by itsjeyd** [comment]
Hi @mattcarter, friendly ping. When you get a minute could you please provide an estimate on when this PR is going to be reviewed by your team?

**Comment by itsjeyd** [comment]
Hey @CodeWithEmad, while this PR is waiting for review it might make sense to resolve merge conflicts (so that we can be sure reviewers will be looking at the latest version of the changes).

CC @mattcarter

**Comment by CodeWithEmad** [comment]
sure @itsjeyd. it's done

**Comment by itsjeyd** [comment]
Thanks @CodeWithEmad!

We'll run tests again soon. CC @e0d

**Comment by itsjeyd** [comment]
@CodeWithEmad It might already be on your radar, but just a friendly nudge about addressing failing tests here.

**Comment by itsjeyd** [comment]
@e0d I had a brief look at the failing build today and it looks like the issue might be unrelated to the changes being introduced here: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

So there is a chance that we'll get a green build here just by re-running the tests. I'm updating labels accordingly. 

CC @CodeWithEmad 

FYI @mphilbrick211, in case you see this on other PRs as well.

**Comment by e0d** [comment]
@itsjeyd I've re-run.  If this doesn't help, I think the @CodeWithEmad should probably rebase.

**Comment by e0d** [comment]
:green_circle: All checks have passed.

**Comment by itsjeyd** [comment]
Hi @mattcarter! We've got a green build here so this PR is ready for review by the Aurora team.

**Comment by itsjeyd** [comment]
Hi @CodeWithEmad, just a quick update about next steps for this PR: It might take a little while longer for engineering review to start but the current plan is to get it reviewed and merged before [Palm](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3552938822/Palm) branches are cut.

Thank you for your patience!

CC @mattcarter @hurtstotouchfire

**Comment by CodeWithEmad** [comment]
Thanks for the update @itsjeyd. I wish I could give you guys a hand on any level.

**Review by leangseu-edx — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/989&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2022-10-17+07:40&entry.1917517419=2023-04-18+18:03&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
