### PR TITLE
feat: update to header with new FPF `pluginProps`

### PR DESCRIPTION
**Pull request by brian-smith-tcril**
backport of https://github.com/openedx/frontend-app-learning/pull/1524

### CODE REVIEW

**Comment by open-craft-grove** [comment]
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8412540704.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8412540704-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8412540704-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8412540704-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413048555.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413048555-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413048555-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413048555-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413547397.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413547397-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413547397-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8413547397-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1525-fadd12.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1525-fadd12.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8426552617-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8426552617-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1525-fadd12-51564656-8426552617-tutor-requirements.txt)

**Review by arbrandes — APPROVED** [review]
👍🏼

**Pull request merged**
