### PR TITLE
fix: first section celebration

### PR DESCRIPTION
**Pull request by dyudyunov**
Fix the first section celebration modal showing logic.

On Nutmeg+ it's shown only after the page reload or after going directly
to the second section from the course home. Going through the course
with the Next/Previous buttons has no effect (which worked on Maple).

Notes:
- the weekly goal has the same showing logic, but I assume that is
correct behavior so no changes are added for it in this commit.
- showing a celebration modal for the first section completion when
going directly to the first unit of the second section seems to be a bug
(reproduces on Maple too)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@dyudyunov Thank you for the contribution, looks like this is ready for our review.

**Comment by dyudyunov** [comment]
> @dyudyunov Thank you for the contribution, looks like this is ready for our review.

hi @natabene 
yes, it's ready

**Review by muselesscreator — COMMENTED** [review]
Please add tests for the new behaviors

**Comment by itsjeyd** [comment]
Hey @dyudyunov, just a quick update that I'm labeling this as `waiting-for-author` for now.

Let us know when you're done [adding tests](https://github.com/openedx/frontend-app-learning/pull/976#pullrequestreview-1204911377) and the changes are ready for review again.

**Comment by dyudyunov** [comment]
hi @itsjeyd @muselesscreator 

please, run checkers and review

**Comment by itsjeyd** [comment]
Thanks @dyudyunov!

@muselesscreator Looks like we're good to go here, please have another look.

**Comment by dyudyunov** [comment]
rebased on the top of master branch

**Comment by mphilbrick211** [comment]
@itsjeyd FYI, I removed the "needs test run" label as tCRIL enabled them.

**Comment by itsjeyd** [comment]
Thanks @mphilbrick211.

Moved to Needs Product Review on the board as that seems to be the immediate next step here. CC @jmakowski1123 

@dyudyunov Looks like there's a small linting issue. If you want to fix that in the meantime, great :) But no rush.

**Comment by dyudyunov** [comment]
> Thanks @mphilbrick211.
> 
> Moved to Needs Product Review on the board as that seems to be the immediate next step here. CC @jmakowski1123
> 
> @dyudyunov Looks like there's a small linting issue. If you want to fix that in the meantime, great :) But no rush.

pushed the fix for the lint issue, please, restart the checkers

**Comment by mphilbrick211** [comment]
@itsjeyd - flagging this for tCRIL to enable tests!

**Comment by ProductRyan** [comment]
@dyudyunov - can you describe what your fix is? where does your code show the celebration?

**Comment by dyudyunov** [comment]
> @dyudyunov - can you describe what your fix is? where does your code show the celebration?

hi @ProductRyan 
This fix doesn't change the place **where** the 1st section celebration is shown but **when**. 
The problem itself: 
- starting from Nutmeg release the 1st section celebration (after the actual completion of the first section) is shown after
  - the page reload
  - or going directly from the course home to the second section
  
 Expected result (as it was on the Maple release):
- user can see the 1st section celebration popup after clicking the "Next" button 
image

**Comment by dyudyunov** [comment]
created a backport to olive: https://github.com/openedx/frontend-app-learning/pull/1044

**Comment by itsjeyd** [comment]
@ProductRyan Thanks for getting product review started here!

For reference, here is a list of related PRs:

* https://github.com/openedx/frontend-app-learning/pull/977 (Nutmeg backport)
* https://github.com/openedx/frontend-app-learning/pull/1044 (Olive backport)

I've put these in Needs Product Review on the contributions board for now; happy to update to In Product Review if you think that's more appropriate.

CC @jmakowski1123

**Comment by jmakowski1123** [comment]
Going forward, this is the master ticket under product review.
Related PRs are:

- https://github.com/openedx/frontend-app-learning/pull/977
- https://github.com/openedx/frontend-app-learning/pull/1044

Removing Product Review label from 977 and 1044.

**Comment by ProductRyan** [comment]
This makes sense - approved. @itsjeyd can you move it, and it's related back ports along?

**Comment by itsjeyd** [comment]
@ProductRyan Sure, done! Thanks for the ping.

@muselesscreator A heads-up that this PR, as well as Nutmeg (#977) and Olive (#1044) backports, should be ready for a final round of engineering review shortly.

@dyudyunov Please resolve merge conflicts. We'll enable tests again once that's done (CC @e0d).

**Comment by dyudyunov** [comment]
@itsjeyd 
>@dyudyunov Please resolve merge conflicts. We'll enable tests again once that's done (CC @e0d).

done

**Comment by itsjeyd** [comment]
Thanks @dyudyunov!

@e0d This is ready for another round of test runs.

**Comment by e0d** [comment]
@itsjeyd tests running.

**Review by leangseu-edx — APPROVED** [review]
LGTM 👍

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/976&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2022-09-14+15:15&entry.1917517419=2023-02-14+21:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
