### PR TITLE
fix: fix tabs urls on progress tab

### LINKED ISSUE #222: [TC_LEARNER_41] > date and course outline pages are blank
**Steps to reproduce:**

1. Go to the progress page on any course in LMS
2. check the `date` and `course outline` pages

**Expected result:**
Pages should have some data in them.
**Actual result:**
Pages are blank
progress page

### PRs

- [x] https://github.com/openedx/frontend-app-learning/pull/1009
- [x] https://github.com/openedx/frontend-app-learning/pull/1011 (Olive backport)

### PR DESCRIPTION
**Pull request by ghassanmas**
Backport port of #1009 to Olive

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey @ghassanmas, thank you for this contribution! Please let us know when it is ready for review.

**Comment by arbrandes** [comment]
@ghassanmas, can you please refactor the backport based on https://github.com/openedx/frontend-app-learning/pull/1009?

**Comment by ghassanmas** [comment]
Can you to repoen, I think it got closed automitcally bceause I pushed same changes by mistake, but I can't reopen it myself

**Comment by ghassanmas** [comment]
Openedx new one #1011

**Pull request closed without merging**
