### PR TITLE
fix: toggle notes visibility button state correctly

### PR DESCRIPTION
**Pull request by ArturGaspar**
## Description

The "Show/Hide Notes" button saves the opposite of its selected state with the `/courses/<course_id>/edxnotes/visibility/` API. This fixes that.

## Testing instructions

1. Enable Notes in a Course Advanced settings
2. Open a Course unit as a Student
3. Use the button
3.1. If the button shows as "Show Notes", click (so it toggles to "Hide Notes"), check that the value sent to `PUT /courses/<course_id>/edxnotes/visibility/` is `{visibility: true}`
3.2. If the button shows as "Hide Notes", click (so it toggles to "Show Notes"), check that the value sent to `PUT /courses/<course_id>/edxnotes/visibility/` is `{visibility: false}`

This independent of the effective visibility of the notes, which might not always correspond to the state in the MFE upon page load due to openedx/wg-build-test-release#227 / openedx/frontend-app-learning#1005.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ArturGaspar!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by tecoholic — APPROVED** [review]
@ArturGaspar :+1:

- [x] I tested this: Verified that the PUT request sends the correct value for visibility
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: checked that the correct value is sent to the `/courses/course-v1:demo+demo+demo/edxnotes/visibility/` endpoint
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by Agrendalath** [comment]
@brian-smith-tcril, would you mind triggering the tests and merging this?

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ArturGaspar 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1170&entry.1484655318=https://github.com/ArturGaspar&entry.752974735=2023-08-25+18:30&entry.1917517419=2023-08-31+14:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by brian-smith-tcril** [comment]
When looking at [the codecov diff on this PR](https://app.codecov.io/gh/openedx/frontend-app-learning/pull/1170/blob/src/index.jsx) it wasn't clear to me that/if code coverage had actually been reduced. After merging it, however, a [coverage change appeared in `SidebarContextProvider.jsx`](https://app.codecov.io/gh/openedx/frontend-app-learning/commit/645ac2cb5f6302f30c20f889903e0ec33905291c/blob/src/courseware/course/sidebar/SidebarContextProvider.jsx).

**Pull request merged**
