### PR TITLE
feat!: remove Transifex calls for OEP-58 | FC-0012

### PR DESCRIPTION
**Pull request by hopewise**
## Breaking change!

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

## Changes

 - Removes all direct use of `tx pull` and `tx push` commands from the micro-frontend in favor
of the [`atlas pull`](https://github.com/openedx/openedx-atlas/) command.
 - Remove source and language translations from the repositories, hence no `.json` files will be committed into the repos. 
 - `src/i18n/index.js` should export and empty array so the `make pull_translations` override it with the dynamic list of languages.
 - Remove the experimental `OPENEDX_ATLAS_PULL` flag to make `atlas pull` the default. 
 - Remove all Transifex related `Makefile` targets and other files.

Test results
------------

 - [ ] Verify that `make pull_translations` works as expected.

<details><summary>make pull_translations test results</summary>

```
# I've run the following commands:
$ make requirements
$ make pull_translations
$ git diff

# Output of the commmands:
make requirements
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!

> @edx/frontend-app-learning@1.0.0-semantically-released prepare /Users/sadaftech/Documents/zeit-labs/frontend-app-learning
> husky install

husky - Git hooks installed
npm WARN bootstrap@4.6.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.6.2 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.

up to date in 11.654s

276 packages are looking for funding
  run `npm fund` for details

make pull_translations

rm -rf src/i18n/messages
mkdir src/i18n/messages
cd src/i18n/messages \
      && atlas pull \
               translations/paragon/src/i18n/messages:paragon \
               translations/frontend-component-header/src/i18n/messages:frontend-component-header \
               translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
               translations/frontend-app-learning/src/i18n/messages:frontend-app-learning
Pulling translation files
 - directory: translations/paragon/src/i18n/messages:paragon translations/frontend-component-header/src/i18n/messages:frontend-component-header translations/frontend-component-footer/src/i18n/messages:frontend-component-footer translations/frontend-app-learning/src/i18n/messages:frontend-app-learning
 - repository: openedx/openedx-translations
 - branch: main
 - filter: Not Specified
 - expand-glob: Not Specified
Creating a temporary Git repository to pull translations into "./translations_TEMP"...
Done.
Setting git sparse-checkout rules...
Done.
Pulling translation files from the repository...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 5), reused 6 (delta 3), pack-reused 0
Receiving objects: 100% (11/11), 27.62 KiB | 353.00 KiB/s, done.
Resolving deltas: 100% (5/5), done.
Your branch is up to date with 'origin/main'.
Done.
Copying translations from "./translations_TEMP/translations/paragon/src/i18n/messages" to "./paragon"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-header/src/i18n/messages" to "./frontend-component-header"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-footer/src/i18n/messages" to "./frontend-component-footer"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-app-learning/src/i18n/messages" to "./frontend-app-learning"...
Done.
Removing temporary directory...
Done.

Translations pulled successfully!
./node_modules/.bin/intl-imports.js paragon frontend-component-header frontend-component-footer frontend-app-learning







```

</details> 

Merge timeline
-----------------------

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

Keep this pull request as a draft to prevent accidental merge.

### Pre-merge checklist

 - [ ] Wait for approval on https://github.com/openedx/wg-translations/issues/20

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @hopewise! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by OmarIthawi** [comment]
Thanks again @hopewise. 

Same comment from the other pull request.

We need to add one more item before we can conclude this PR:

 - Run `make pull_translations` locally and post a git diff. I've updated the template so you can copy the `Test results` section from within: https://github.com/Zeit-Labs/fc-0012-pr-template/blob/main/mfe-deprecate-tx.md?plain=1#L14

**Review by OmarIthawi — APPROVED** [review]
Thanks @hopewise! 

Confirming that this PR is ready to be merged as soon as https://github.com/openedx/wg-translations/issues/20 is given green light.

**Comment by OmarIthawi** [comment]
@hopewise would you mind checking tests? They're failing:

 - https://github.com/openedx/frontend-app-learning/actions/runs/6371115803/job/17318126375?pr=1198

**Comment by itsjeyd** [comment]
Hey @hopewise, thanks for these changes!

It looks like they are part of FC-0012. Would you mind [mentioning that in the PR title](https://github.com/openedx/openedx-translations/pull/146#issuecomment-1516307485)?

**Comment by OmarIthawi** [comment]
@itsjeyd @timmc-edx @brian-smith-tcril this is ready for merge.

**Review by brian-smith-tcril — APPROVED** [review]

**Review by leangseu-edx — APPROVED** [review]

**Review by leangseu-edx — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@hopewise 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1198&entry.1484655318=https://github.com/hopewise&entry.752974735=2023-09-29+11:17&entry.1917517419=2024-03-18+19:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
