### PR TITLE
FC-0001: Replace PDF course certificate view code

### PR DESCRIPTION
**Pull request by ruzniaievdm**
**Description:**
This DEPR ticket covers the removal of the code in edx-platform that allows PDF certificates to be viewed.
This is the frontend part of the removal
PR to `edx-platform` - https://github.com/openedx/edx-platform/pull/30397

[Github issue](https://github.com/openedx/public-engineering/issues/27)
[Original Jira Issue](https://openedx.atlassian.net/browse/DEPR-157)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6682](https://openedx.atlassian.net/browse/OSPR-6682) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@dianakhuang Will you review this?

**Comment by natabene** [comment]
@ruzniaievdm Can you look into the failing test?

**Review by dianakhuang — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ruzniaievdm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/946&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-05-16+08:54&entry.1917517419=2022-06-13+13:15&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
